.TH CURATOR "1" "December 2016" "curator 4.2" "User Commands"
.SH NAME
\fBcurator\fP \- Elasticsearch time-series index manager

.SH SYNOPSIS
curator_cli [\-h] [\-v] [\-\-host HOST] [\-\-url_prefix URL_PREFIX]
[\-\-port PORT] [\-\-use_ssl] [\-\-http_auth AUTH]
[\-\-timeout TIMEOUT] [\-\-master\-only] [\-\-dry\-run]
[\-\-loglevel LOG_LEVEL] [\-\-logfile LOG_FILE]
[\-\-logformat LOGFORMAT]
\fICOMMAND\fP [\fICOMMAND_OPTS\fP] \fIARGUMENTS\fP

.SH DESCRIPTION
\fBcurator\fP helps manage Elasticsearch time-series indices. It provides an
easy way to perform index administration tasks, such as managing aliases,
optimizing indices, changing the replica count and modifying index allocation
using routing tags.

.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
show program usage and exit
.TP
\fB\-v\fR, \fB\-\-version\fR
show program's version number and exit
.TP
\fB\-\-host\fR HOST
Elasticsearch host. Default: localhost
.TP
\fB\-\-url_prefix\fR URL_PREFIX
Elasticsearch HTTP url prefix. Default: none
.TP
\fB\-\-port\fR PORT
Elasticsearch port. Default: 9200
.TP
\fB\-\-use_ssl\fR
Connect to Elasticsearch through SSL. Default: false
.TP
\fB\-\-certificate\fR
Path to certificate to use for SSL validation.
.TP
\fB\-\-client\-cert\fR
Path to file containing SSL certificate for client auth.
.TP
\fB\-\-ssl\-no\-validate\fR
Do not validate SSL certificate
.TP
\fB\-\-http_auth\fR AUTH
Use Basic Authentication ex: user:pass Default: None
.TP
\fB\-\-timeout\fR TIMEOUT
Connection timeout in seconds.
.TP
\fB\-\-master\-only\fR
Verify that the node is the elected master before
continuing
.TP
\fB\-\-dry\-run\fR
If true, does not perform any changes to the
Elasticsearch indices.
.TP
\fB\-\-loglevel\fR LOG_LEVEL
Log level
.TP
\fB\-\-logfile\fR LOG_FILE
log file
.TP
\fB\-\-logformat\fR LOGFORMAT
Log output format [default|logstash]. Default: default

.SH COMMANDS
Each of the following commands accepts a number of options and positional
arguments. Run \fBcurator\fP \fICOMMAND\fP \fB\-\-help\fR for command\-specific
help. Available commands are:
.TP
.B allocation
Apply required index routing allocation rule
.TP
.B close
Close indices
.TP
.B delete_indices
Delete indices
.TP
.B delete_snapshots
Delete snapshots
.TP
.B forcemerge
forceMerge index/shard segments
.TP
.B open
Open indices
.TP
.B replicas
Change replica count of indices
.TP
.B show_indices
Show indices
.TP
.B show_snapshots
Show snapshots
.TP
.B snapshot
Take snapshots of indices

.SH "EXIT CODES"
Exit codes will indicate success or failure.

.TP
0
Success
.TP
1
Failure
.TP
-1
An exception was raised that does not result in an exit code of 1

.SH "SEE ALSO"
.BR es_repo_mgr (1) "" ", " curator (1)

Additional documentation for
.B curator_cli
can be found at the project's wiki at
https://github.com/elasticsearch/curator/wiki and (on Debian systems) under
.BR /usr/share/doc/elasticsearch-curator/reference.txt.gz .

.SH AUTHOR
\fBcurator\fP was originally written by Aaron Mildenstein
<aaron@mildensteins.com>. It is currently maintained by Elasticsearch
<http://www.elasticsearch.org/>.

This manual page was written by Apollon Oikonomopoulos <apoikos@debian.org> for
the Debian project (but may be used by others).

.SH LICENSE
This software is released under the Apache License, Version 2.0. See
/usr/share/doc/elasticsearch-curator/copyright for more details.

Copyright 2011-2016 Elasticsearch and contributors.
