.TH CURATOR "1" "December 2016" "curator 4.2" "User Commands"
.SH NAME
\fBcurator\fP \- Elasticsearch time-series index manager

.SH SYNOPSIS
curator [\-\-config CONFIG.YML] [\-\-dry\-run] ACTION_FILE.YML

.SH DESCRIPTION
\fBcurator\fP helps manage Elasticsearch time-series indices. It provides an
easy way to perform index administration tasks, such as managing aliases,
optimizing indices, changing the replica count and modifying index allocation
using routing tags.

.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
show program usage and exit
.TP
\fB\-v\fR, \fB\-\-version\fR
show program's version number and exit
.TP
\fB\-\-config\fR PATH
Path to configuration file. Default: ~/.curator/curator.yml
.TP
\fB\-\-dry\-run\fR
Do not perform any changes.

ACTION_FILE is a YAML curator action file. For more information on action files, consult
.BR /usr/share/doc/elasticsearch-curator/reference.txt.gz .

.SH "EXIT CODES"
Exit codes will indicate success or failure.

.TP
0
Success
.TP
1
Failure
.TP
-1
An exception was raised that does not result in an exit code of 1

.SH "SEE ALSO"
.BR es_repo_mgr (1) "" ", " curator_cli (1)

Additional documentation for
.B curator
can be found at the project's wiki at
https://github.com/elasticsearch/curator/wiki and (on Debian systems) under
.BR /usr/share/doc/elasticsearch-curator/reference.txt.gz .

.SH AUTHOR
\fBcurator\fP was originally written by Aaron Mildenstein
<aaron@mildensteins.com>. It is currently maintained by Elasticsearch
<http://www.elasticsearch.org/>.

This manual page was written by Apollon Oikonomopoulos <apoikos@debian.org> for
the Debian project (but may be used by others).

.SH LICENSE
This software is released under the Apache License, Version 2.0. See
/usr/share/doc/elasticsearch-curator/copyright for more details.

Copyright 2011-2016 Elasticsearch and contributors.
