.TH ES_REPO_MGR "1" "December 2016" "curator 4.2" "User Commands"
.SH NAME
\fBes_repo_mgr\fP \- snapshot repository manager for Elasticsearch
.BR curator (1).

.SH SYNOPSIS
\fBes_repo_mgr\fP [\-h] [\-v] [\-\-host HOST] [\-\-url_prefix URL_PREFIX]
[\-\-port PORT] [\-\-ssl] [\-\-auth AUTH] [\-t TIMEOUT] [\-n]
[\-D] [\-\-loglevel LOG_LEVEL] [\-l LOG_FILE]
[\-\-logformat LOGFORMAT]
\fICOMMAND\fP [\fICOMMAND_OPTS\fP] \fIARGUMENTS\fP

.SH DESCRIPTION
\fBes_repo_mgr\fP is a helper script to assist in creating Elasticsearch index
snapshot repositories. At this time, only \fBfs\fP and \fBs3\fP types are
supported. Please be sure to read the documentation for the indicated type
before creating a repository. For example, each node using a \fBfs\fP type
repository must be able to access the same shared filesystem, in the same path,
identified by \-\-location.

.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
show this program usage and exit
.TP
\fB\-\-config\fR PATH
Path to configuration file. Default: ~/.curator/curator.yml

.SH COMMANDS
Each command accepts a number of options and positional arguments. Run
\fBes_repo_mgr\fP \fICOMMAND\fP \fB\-\-help\fP for command\-specific help. The
following commands are available:
.TP
.B create
Create a new repository
.TP
.B delete
Delete a named repository
.TP
.B show
Show all repositories

.SH "SEE ALSO"
.BR curator (1) "" ", " curator_cli (1)

Additional documentation for
.B es_repo_mgr
can be found at curator's wiki at
https://github.com/elasticsearch/curator/wiki. On Debian systems, information
about the curator.yml configuration file can be found in
.BR /usr/share/doc/elasticsearch-curator/reference.txt.gz .

.SH AUTHOR
\fBcurator\fP was originally written by Aaron Mildenstein
<aaron@mildensteins.com>. It is currently maintained by Elasticsearch
<http://www.elasticsearch.org/>.

This manual page was written by Apollon Oikonomopoulos <apoikos@debian.org> for
the Debian project (but may be used by others).

.SH LICENSE
This software is released under the Apache License, Version 2.0. See
/usr/share/doc/elasticsearch-curator/copyright for more details.

Copyright 2011-2016 Elasticsearch and contributors.
